### ISSUE TITLE
Stop using rbd command

### ISSUE THREAD

**Issue by guilhem** [contiv/volplugin#102] opened 2016-01-06 17:33 UTC
I want to use this plugin on coreos but `rbd` isn't available.

I wonder why not using https://github.com/ceph/go-ceph/tree/master/rbd for any rbd operation? It seems to be more stable (thanks to godep) and with less dependency on an external tool who can change from different versions.

**Comment by erikh** [comment] 2016-01-06 17:47
It can't map RBD devices, a key component to this. The decision to do so was spurred by a previous conversation with the author of that project. https://github.com/contiv/volplugin/issues/10#issuecomment-136494235

So, we developed https://github.com/contiv/librbd to do just this and for this very reason, but then the ceph API failed us with a limited version to determine configuration via its C interface (Ceph is principally written in C++), some of which is necessary to prime RBD map operations.

I would love to do something about this but there are a lot of moving parts in play and I only manage one of them, so I made the most conservative choice I could after all the efforts in directions that had not paid off. I understand this may leave you frustrated. If you have advice on how to get nested configuration out of Ceph's librados C interface, or know how to `rbd map` without the `rbd` tool otherwise, please let me know... I am frustrated too! :)

I do have to close this however since I can't actually resolve this on my own.

**Closed by erikh** 2016-01-06 17:47 UTC

**Comment by guilhem** [comment] 2016-01-06 18:03
@erikh I may be totally wrong, but I look to http://cephnotes.ksperis.com/blog/2014/01/09/map-rbd-kernel-without-install-ceph-common and especially http://cephnotes.ksperis.com/downloads/rbdmap to see what sysfs call he does.

I don't really understand why using lib(k)rbd when we directly have sysfs ;)

**Comment by erikh** [comment] 2016-01-06 20:22
yes this is what contiv/librbd does. Now I need the bits that pull out the monitor addresses from the configuration files. in C.

**Comment by erikh** [comment] 2016-01-06 20:48
Sorry to be so stubborn and not explain much. Hopefully I can detail this a little better below:

So Ceph stores configurations in two different formats.

One is single level:

```
mon addr = 192.168.24.10,192.168.24.11,192.168.24.12
```

The other is multi-level, ini-style:

```
[mon]
   addr = 192.168.24.10,192.168.24.11,192.168.24.12
```

The problem is this second format, which I cannot figure out how to parse with the `librados` C toolkit which Ceph provides to do so because it only handles k/v pairs, not full configurations. If you have any ideas here, I'm really all ears. Personally writing a separate parser of dubious compatibility is probably not the right thing to do here.

**Comment by guilhem** [comment] 2016-01-07 11:32
@erikh don't worry, I just try to understand a little more and expose a problem on platform where `rbd` isn't available (but I can bypass it with a container ;)).
You seems to have far more knowledge than me :) I'm trusting you.

About configuration... Ceph is more bloated on this part than I expect. I will ask people from ceph if there will be in FOSDEM to talk about it.
I dream to see a direct integration to etcd/consul

**Comment by guilhem** [comment] 2016-01-07 11:36
@erikh don't know if it can help, I created a public slack for ceph:
here is for the invitation http://slackin-ceph-public.herokuapp.com/
and link for slack https://ceph-public.slack.com

I may create a channel to talk about go lib

It's not official for the moment, but I try to convince ceph team to use it

**Comment by erikh** [comment] 2016-01-08 14:03
@guilhem volplugin provides the etcd backend to coordinate ceph. It's not direct, but it's robust and complete (at least, best I can tell from our test suite). It also implements TTL-backed operations so that a host crash will not keep locks on the volumes.

I'm actually in China for the next 3 weeks on vacation, so I'm going to pass on slack for now. Note that they do have a set of IRC channels on OFTC if you're looking for additional help.
