### ISSUE TITLE
volume mounted multiple times

### ISSUE THREAD

**Issue by tsaridas** [contiv/volplugin#282] opened 2016-05-28 23:17 UTC
Hello,

I tested the plugin with make demo and tried the scenario to mount the same volume multiple times.

What I noticed is that the first time I try to mount a volume which is already mounted somewhere else it fails with message 
```
docker: Error response from daemon: VolumeDriver.Mount: Mountpoint already in use <nil>.
```
The second time I try though the volume mounts normally and I could write from both containers and read from them.
I tested on the same host and did not try running the container in a different host.

**Comment by erikh** [comment] 2016-05-28 23:50
Interesting. I will look into this today. Thanks for the report.

**Comment by erikh** [comment] 2016-05-29 01:04
So, this is what I have done so far, all on a single host of a 3 host cluster (our standard setup):

1. Attempted to acquire a lock in one shell with a loop while another held the lock
1. Verified that releasing the lock does indeed stop the other loop (as it acquires the lock, entering a container)
1. Verified that starting a stopped container -- that was holding the lock previously -- could not acquire the lock.

I'm not quite sure what you're running into yet. Can you tell me what policy you uploaded to volplugin and any details about  your environment?

**Comment by dseevr** [comment] 2016-05-29 01:37
I was able to reproduce this by following these steps:

1. Ran `make demo` and ssh'd into mon0
1. Uploaded policy1.json
1. Created a volume using policy1
1. Ran `while [ true ]; do docker run -it -v policy1/foo:/mnt alpine sh; done` in Terminal 1
1. Ran `while [ true ]; do docker run -it -v policy1/foo:/mnt alpine sh; done` in Terminal 2
1. Sent EOF to Terminal 1 to exit sh and Terminal 2 immediately grabbed a lock on the volume and started sh
1. Sent EOF to Terminal 2 to exit sh
1. Repeated the last two steps a few times

I ended up with both containers running with /dev/rbd0 mounted.

**Comment by erikh** [comment] 2016-05-29 01:38
Thanks for the details. I think I have a fix.

**Comment by dseevr** [comment] 2016-05-29 01:49
I was not able to reproduce the issue by having two different hosts trying to create a container using the same volume in a tight loop.

**Comment by erikh** [comment] 2016-05-29 01:56
I've submitted #283 which I believe has the fix for this issue, btu I am not testing this directly. I am testing something very similar though which is why I thought this was just fine. Computers.

Anyways, you may wish to track this ticket.

**Comment by erikh** [comment] 2016-05-29 02:29
So, the more I think about this, the less trouble it will be and the better off everyone's lives will be if we just let this happen instead of trying to prevent it. I think what we should do instead of the current behavior is:

1. Track all mount requests for a specific volume into a "mount counter"
1. When mount count > 1, just return the path of the mounted volume
1. When mount count < 1, actually unmap/unmount.

This will be a change that spans all drivers, and safely so.

**Comment by dseevr** [comment] 2016-05-29 02:31
SGTM

**Comment by erikh** [comment] 2016-05-29 02:31
@unclejack @mapuri @jainvipin strong opinions here?

**Comment by jainvipin** [comment] 2016-05-29 04:08
@erikh tracking mounts using `mount counter` sounds like a good idea. counter increment must be lock safe.

**Comment by erikh** [comment] 2016-05-29 05:18
Yep, sorry I omitted that detail.

**Comment by erikh** [comment] 2016-05-30 07:26
#286 was provided to resolve this issue as prescribed above.

**Comment by tsaridas** [comment] 2016-05-30 09:26
Hello,
I can confirm.
I now get message : 

```
docker: Error response from daemon: VolumeDriver.Mount: Mountpoint already in use <nil>.
See 'docker run --help'.
```

Thanks for your support.

**Comment by erikh** [comment] 2016-05-30 09:28
We identified it as a race; so you will not necessarily see it every 
time.

-Erik

**Comment by tsaridas** [comment] 2016-05-30 12:23
Hi again,

Same problem.

```
docker run -it -v policy1/image:/mnt ubuntu bash
docker: Error response from daemon: VolumeDriver.Mount: Volume could not be mounted Failed to mount RBD dev "/dev/rbd1": device or resource busy
	github.com/contiv/volplugin/storage/backend/ceph.(*Driver).Mount [ceph.go 228]
	github.com/contiv/volplugin/volplugin.(*DaemonConfig).mount [handlers.go 305]
	github.com/contiv/volplugin/volplugin.(*DaemonConfig).(github.com/contiv/volplugin/volplugin.mount)-fm [volplugin.go 149]
	github.com/contiv/volplugin/volplugin.logHandler.func1 [volplugin.go 182]
	net/http.HandlerFunc.ServeHTTP [server.go 1618]
	github.com/contiv/volplugin/vendor/github.com/gorilla/mux.(*Router).ServeHTTP [mux.go 98]
	net/http.serverHandler.ServeHTTP [server.go 2081]
	net/http.(*conn).serve [server.go 1472]
	runtime.goexit [asm_amd64.s 1998].
See 'docker run --help'.
root@sbb:~# docker run -it -v policy1/image:/mnt ubuntu bash
root@1af3deae4c92:/# exit
```

```
DEBU[1282] Dispatching Mount with {"Name":"policy1/image"}
INFO[1282] Mounting volume "policy1/image"
DEBU[1282] Mapped: &storage.Mount{Device:"/dev/rbd1", Path:"", DevMajor:0x0, DevMinor:0x0, Volume:storage.Volume{Name:"policy1/image", Size:0x0, Source:"", Params:storage.Params{"pool":"rbd"}}}
DEBU[1282] Mapped: &storage.Mount{Device:"/dev/rbd2", Path:"", DevMajor:0x0, DevMinor:0x0, Volume:storage.Volume{Name:"policy1/image", Size:0x0, Source:"", Params:storage.Params{"pool":"rbd"}}}
DEBU[1282] Reporting mount &config.UseMount{Volume:"policy1/image", Hostname:"sbb.zh.teralytics.net", Reason:"Mount"}: <nil>
DEBU[1282] mapped volume "policy1.image" as "/dev/rbd2"
DEBU[1282] Dispatching Unmount with {"Name":"policy1/image"}
INFO[1282] Unmounting volume "policy1/image"
DEBU[1282] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1282] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 272.542021ms (exit status 16) ()
ERRO[1282] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1282] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1283] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 272.736377ms (exit status 16) ()
ERRO[1283] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1283] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1283] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 274.348267ms (exit status 16) ()
ERRO[1283] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1283] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1283] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 271.924634ms (exit status 16) ()
ERRO[1283] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1284] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1284] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 274.618107ms (exit status 16) ()
ERRO[1284] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1284] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1284] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 274.561093ms (exit status 16) ()
ERRO[1284] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1284] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1285] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 274.290378ms (exit status 16) ()
ERRO[1285] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1285] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1285] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 272.169181ms (exit status 16) ()
ERRO[1285] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1285] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1285] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 273.519654ms (exit status 16) ()
ERRO[1285] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1285] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
ERRO[1286] Could not unmap volume "policy1.image" (device "/dev/rbd1"): Command: [rbd unmap /dev/rbd1], Exit status 16, Runtime 274.734447ms (exit status 16) ()
ERRO[1286] Retrying to unmap volume "policy1.image" (device "/dev/rbd1")...
DEBU[1286] Unmapping volume rbd/policy1.image at device "/dev/rbd1"
DEBU[1286] Dispatching Mount with {"Name":"policy1/image"}
INFO[1286] Mounting volume "policy1/image"
DEBU[1286] Mapped: &storage.Mount{Device:"/dev/rbd1", Path:"", DevMajor:0x0, DevMinor:0x0, Volume:storage.Volume{Name:"policy1/image", Size:0x0, Source:"", Params:storage.Params{"pool":"rbd"}}}
DEBU[1286] Mapped: &storage.Mount{Device:"/dev/rbd2", Path:"", DevMajor:0x0, DevMinor:0x0, Volume:storage.Volume{Name:"policy1/image", Size:0x0, Source:"", Params:storage.Params{"pool":"rbd"}}}
DEBU[1286] Mapped: &storage.Mount{Device:"/dev/rbd3", Path:"", DevMajor:0x0, DevMinor:0x0, Volume:storage.Volume{Name:"policy1/image", Size:0x0, Source:"", Params:storage.Params{"pool":"rbd"}}}
DEBU[1286] Reporting mount &config.UseMount{Volume:"policy1/image", Hostname:"sbb.zh.teralytics.net", Reason:"Mount"}: <nil>
DEBU[1286] mapped volume "policy1.image" as "/dev/rbd1"
```

```
cat policy1.json
{
  "backends": {
    "crud": "ceph",
    "mount": "ceph",
    "snapshot": "ceph"
  },
  "unlocked": false,
  "driver": {
    "pool": "rbd"
  },
  "create": {
    "size": "10MB",
    "filesystem": "ext4"
  },
  "runtime": {
    "snapshots": false,
    "snapshot": {
      "frequency": "30m",
      "keep": 20
    },
    "rate-limit": {
      "write-iops": 1000,
      "read-iops": 1000,
      "write-bps": 100000000,
      "read-bps": 100000000
    }
  },
  "filesystems": {
    "ext4": "mkfs.ext4 -m0 %",
    "falsefs": "/bin/false"
  }
}
```

I couldn't mount the volume from another host though.

I tested with  "unlocked": true, and I can mount volume from different hosts.

I also get the below error. Dunno if this whole thing has something to do with etcd.

```
ERRO[0163] Could not report mount for host "-unlocked-" to master "ffs.zh.teralytics.net:9005": Status was not 200: was 500: "Could not refresh mount information 100: Key not found (/volplugin/users/mount/policy2/image) [404]"
```

**Comment by erikh** [comment] 2016-05-30 21:38
Yep, #286 fixes this issue, but creates a new one regarding NFS, so I am fixing that now.

**Comment by erikh** [comment] 2016-05-31 23:10
Do you get the unlocked error trying to mount across hosts? or just on the same host?

**Comment by erikh** [comment] 2016-05-31 23:11
I just added that feature last week, beware, there are probably still a few bugs. :)

**Comment by erikh** [comment] 2016-06-02 15:10
Check out the nightly build in the next day. It will have the fixes you need, I think.

**Closed** 2016-06-02 15:10 UTC

**Comment by CBR09** [comment] 2016-06-03 09:38
Same issue, try to use volume multi time cause many error :(

**Comment by erikh** [comment] 2016-06-03 13:38
Try tomorrow's release and tell me if things are still broken.

Or are you talking about across multiple hosts?

**Comment by CBR09** [comment] 2016-06-06 08:07
I've tested with latest release, use one rbd image for multi container seem okay, but it's not my desire. I will open new issue.

**Comment by erikh** [comment] 2016-06-06 09:36
OK. Thanks, we will do our best to accommodate the needs here, but I ran 
into some technical barriers implementing local locks. Namely, the 
existence checks I was using were more like schrödinger's cat than a 
light switch.

In reality, the technical barrier is probably me here. Some ideas we can 
try in the near future:

Perhaps once Docker 1.12 is out, the volumes API will have a new unique 
identifier we can key on, this could make the locking schemes much 
richer. I need to investigate a little more. If you're willing to wait 
for that, of course. :)

We could also delegate this to the storage driver, which could use 
rbd-lock to acquire its ceph volumes. We didn't have much success with 
RBD locking before but this would be an excellent use case for it. I see 
this as potentially necessary for a number of drivers we may write soon 
as well.
