### ISSUE TITLE
Can't create volume

### ISSUE THREAD

**Issue by magicrobotmonkey** [contiv/volplugin#90] opened 2015-12-16 22:44 UTC
I've got a straightforward test setup going. With rbd I can create, map and mount volumes. 

Running:
```bash
./volmaster --etcd http://172.16.31.215:24 --debug &
./volplugin --debug &
docker volume create -d volplugin --name='tenant1/test3'
```

I get 
```bash
#( from volmaster)
DEBU[0109] Dispatching /create with {"tenant":"tenant1","volume":"test3","opts":{}}
DEBU[0110] mapped volume "tenant1.test3" as "/dev/rbd1"
WARN[0110] Returning HTTP error handling plugin negotiation: Creating volume exit status 1

#( from volplugin) 
DEBU[0097] Dispatching Create with {"Name":"tenant1/test3","Opts":{}}
WARN[0098] Returning HTTP error handling plugin negotiation: Could not determine tenant configuration Status was not 200: was 500: "Creating volume exit status 1"

#(from docker)
Error response from daemon: Plugin Error: VolumeDriver.Create, {"Mountpoint":"","Err":"Could not determine tenant configuration Status was not 200: was 500: \"Creating volume exit status 1\""}
```
The end result is that the rbd volume is created, mappped, and the ext4 fs is created on it, but `volcli volume list-all` doesnt show it. This is what's in etcd:
```
/volplugin/volumes
/volplugin/volumes/tenant1
/volplugin/users
/volplugin/users/tenant1
/volplugin/users/tenant1/test3
/volplugin/tenants
/volplugin/tenants/tenant1
``` 

I'm not sure what other debugging I can do on this. It's not clear to me what step of the create is failing.

**Comment by erikh** [comment] 2015-12-16 23:22
Hi! This error usually surfaces when you have not uploaded a tenant configuration first. I see that you have one in etcd, but you do not run the command above. Can you show me your tenant configuration + the commands you used to upload it?

**Comment by erikh** [comment] 2015-12-16 23:29
I see what's happening. I'll try to address this tomorrow or later tonight. Thanks for the report.

If you could give me more information on your ceph cluster, that would help a lot.

**Comment by erikh** [comment] 2015-12-17 04:51
What version are you using? Can I see your tenant configuration as well?

**Comment by magicrobotmonkey** [comment] 2015-12-17 14:53
Tenant config is nearly straight out of the examples, except I bumped up the size:
```javascript
{
  "default-options": {
    "pool": "rbd",
    "size": "10GB",
    "snapshots": true,
    "snapshot": {
      "frequency": "30m",
      "keep": 20
    }
  }
}
```

ceph I got ambitious and went with Infernalis: `ceph version 9.2.0-754-g6bf5c87 (6bf5c8755d7f99ec49025bc5e2a4c2cf973f20c9)`

**Comment by erikh** [comment] 2015-12-17 19:19
ok, we're testing here on infernalis so NBD. :) I think there's a HTTP timeout here that's defeating us but I'm not entirely sure yet. I'll investigate and get back to you later today.

**Comment by erikh** [comment] 2015-12-24 10:47
Sorry I haven't gotten back to you yet. No matter what I do, I cannot seem to simulate this error yet. I'm putting it on the back burner for now. If you find the time to try again and run into the same issue, please do let me know.

**Comment by erikh** [comment] 2016-01-20 19:07
I'm going to close this, please let me know if it needs to be reopened as I cannot reproduce it.

**Closed by erikh** 2016-01-20 19:07 UTC
